<?php

namespace SnowTricksBundle\Repository;

/**
 * TricksPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
