<?php

namespace SnowTricksBundle\Repository;

/**
 * TricksVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
