<?php

namespace SnowTricksBundle\Repository;

/**
 * UserPictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPictureRepository extends \Doctrine\ORM\EntityRepository
{
}
